application: openpowersystem
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /output
  static_dir: output

- url: /.*
  script: openpowersystem.py
